#!/bin/bash
# 更新版本号的脚本，遵循语义化版本控制

set -e

VERSION_FILE="version.json"
OUTPUT_FILE="src/lib/version.ts"

# 读取当前版本
if [ -f "$VERSION_FILE" ]; then
    CURRENT_VERSION=$(grep '"version":' "$VERSION_FILE" | sed -E 's/.*"([^"]+)".*/\1/')
else
    CURRENT_VERSION="1.0.0"
fi

echo "当前版本: $CURRENT_VERSION"

# 解析版本号
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

# 增加 patch 号
NEW_PATCH=$((PATCH + 1))
NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

# 获取构建时间
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# 更新版本文件
cat > "$VERSION_FILE" << EOF
{
  "version": "$NEW_VERSION",
  "buildTime": "$BUILD_TIME"
}
EOF

# 生成 TypeScript 模块
cat > "$OUTPUT_FILE" << EOF
// This file is auto-generated by scripts/update-version.sh
// Do not edit this file manually!

export const VERSION = "$NEW_VERSION";
export const BUILD_TIME = "$BUILD_TIME";

export function getVersionInfo() {
  return {
    version: VERSION,
    buildTime: BUILD_TIME,
    timestamp: new Date().toISOString(),
  };
}
EOF

echo "已更新到版本: $NEW_VERSION"
echo "构建时间: $BUILD_TIME"
echo "版本模块已生成: $OUTPUT_FILE"
